<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname(dirname($vendorDir));

return array(
    'Archetype\\Vendor\\voku\\' => array($vendorDir . '/voku/portable-ascii/src/voku'),
    'Archetype\\Vendor\\Symfony\\Polyfill\\Php83\\' => array($vendorDir . '/symfony/polyfill-php83'),
    'Archetype\\Vendor\\Symfony\\Polyfill\\Mbstring\\' => array($vendorDir . '/symfony/polyfill-mbstring'),
    'Archetype\\Vendor\\Symfony\\Contracts\\Translation\\' => array($vendorDir . '/symfony/translation-contracts'),
    'Archetype\\Vendor\\Symfony\\Component\\Translation\\' => array($vendorDir . '/symfony/translation'),
    'Archetype\\Vendor\\Symfony\\Component\\Clock\\' => array($vendorDir . '/symfony/clock'),
    'Archetype\\Vendor\\Ramsey\\Uuid\\' => array($vendorDir . '/ramsey/uuid/src'),
    'Archetype\\Vendor\\Ramsey\\Collection\\' => array($vendorDir . '/ramsey/collection/src'),
    'Archetype\\Vendor\\Psr\\SimpleCache\\' => array($vendorDir . '/psr/simple-cache/src'),
    'Archetype\\Vendor\\Psr\\Log\\' => array($vendorDir . '/psr/log/src'),
    'Archetype\\Vendor\\Psr\\Container\\' => array($vendorDir . '/psr/container/src'),
    'Archetype\\Vendor\\Psr\\Clock\\' => array($vendorDir . '/psr/clock/src'),
    'Archetype\\Vendor\\Psr\\Cache\\' => array($vendorDir . '/psr/cache/src'),
    'Archetype\\Vendor\\Laravel\\SerializableClosure\\' => array($vendorDir . '/laravel/serializable-closure/src'),
    'Archetype\\Vendor\\Illuminate\\Support\\' => array($vendorDir . '/illuminate/support', $vendorDir . '/illuminate/collections', $vendorDir . '/illuminate/conditionable', $vendorDir . '/illuminate/macroable'),
    'Archetype\\Vendor\\Illuminate\\Pipeline\\' => array($vendorDir . '/illuminate/pipeline'),
    'Archetype\\Vendor\\Illuminate\\Events\\' => array($vendorDir . '/illuminate/events'),
    'Archetype\\Vendor\\Illuminate\\Database\\' => array($vendorDir . '/illuminate/database'),
    'Archetype\\Vendor\\Illuminate\\Contracts\\' => array($vendorDir . '/illuminate/contracts'),
    'Archetype\\Vendor\\Illuminate\\Container\\' => array($vendorDir . '/illuminate/container'),
    'Archetype\\Vendor\\Illuminate\\Bus\\' => array($vendorDir . '/illuminate/bus'),
    'Archetype\\Vendor\\Doctrine\\Inflector\\' => array($vendorDir . '/doctrine/inflector/lib/Doctrine/Inflector'),
    'Archetype\\Vendor\\Doctrine\\Deprecations\\' => array($vendorDir . '/doctrine/deprecations/src'),
    'Archetype\\Vendor\\Doctrine\\DBAL\\' => array($vendorDir . '/doctrine/dbal/src'),
    'Archetype\\Vendor\\Doctrine\\Common\\Cache\\' => array($vendorDir . '/doctrine/cache/lib/Doctrine/Common/Cache'),
    'Archetype\\Vendor\\Doctrine\\Common\\' => array($vendorDir . '/doctrine/event-manager/src'),
    'Archetype\\Vendor\\Carbon\\Doctrine\\' => array($vendorDir . '/carbonphp/carbon-doctrine-types/src/Carbon/Doctrine'),
    'Archetype\\Vendor\\Carbon\\' => array($vendorDir . '/nesbot/carbon/src/Carbon'),
    'Archetype\\Vendor\\Brick\\Math\\' => array($vendorDir . '/brick/math/src'),
    'Archetype\\Vendor\\Analog\\' => array($vendorDir . '/analog/analog/lib/Analog'),
    'Archetype\\' => array($baseDir . '/src'),
);
